services:
  - type: web
    name: scorerent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scorerent-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: scorerent-db
    plan: free
